// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: encoder.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncodeTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Texts []string `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
}

func (x *EncodeTextRequest) Reset() {
	*x = EncodeTextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encoder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncodeTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeTextRequest) ProtoMessage() {}

func (x *EncodeTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encoder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeTextRequest.ProtoReflect.Descriptor instead.
func (*EncodeTextRequest) Descriptor() ([]byte, []int) {
	return file_encoder_proto_rawDescGZIP(), []int{0}
}

func (x *EncodeTextRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

type EncodeTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Embedding []*Embedding `protobuf:"bytes,2,rep,name=embedding,proto3" json:"embedding,omitempty"`
}

func (x *EncodeTextResponse) Reset() {
	*x = EncodeTextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encoder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncodeTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeTextResponse) ProtoMessage() {}

func (x *EncodeTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encoder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeTextResponse.ProtoReflect.Descriptor instead.
func (*EncodeTextResponse) Descriptor() ([]byte, []int) {
	return file_encoder_proto_rawDescGZIP(), []int{1}
}

func (x *EncodeTextResponse) GetEmbedding() []*Embedding {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type Embedding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Point []float32 `protobuf:"fixed32,3,rep,packed,name=point,proto3" json:"point,omitempty"`
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encoder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_encoder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_encoder_proto_rawDescGZIP(), []int{2}
}

func (x *Embedding) GetPoint() []float32 {
	if x != nil {
		return x.Point
	}
	return nil
}

var File_encoder_proto protoreflect.FileDescriptor

var file_encoder_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x22, 0x29, 0x0a, 0x11, 0x45, 0x6e, 0x63, 0x6f,
	0x64, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x65, 0x78, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x65,
	0x78, 0x74, 0x73, 0x22, 0x46, 0x0a, 0x12, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x65, 0x78,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x65, 0x6d, 0x62,
	0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x21, 0x0a, 0x09, 0x45,
	0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x02, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x50,
	0x0a, 0x07, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x0a, 0x45, 0x6e, 0x63,
	0x6f, 0x64, 0x65, 0x54, 0x65, 0x78, 0x74, 0x12, 0x1a, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x72, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x45, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_encoder_proto_rawDescOnce sync.Once
	file_encoder_proto_rawDescData = file_encoder_proto_rawDesc
)

func file_encoder_proto_rawDescGZIP() []byte {
	file_encoder_proto_rawDescOnce.Do(func() {
		file_encoder_proto_rawDescData = protoimpl.X.CompressGZIP(file_encoder_proto_rawDescData)
	})
	return file_encoder_proto_rawDescData
}

var file_encoder_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_encoder_proto_goTypes = []interface{}{
	(*EncodeTextRequest)(nil),  // 0: encoder.EncodeTextRequest
	(*EncodeTextResponse)(nil), // 1: encoder.EncodeTextResponse
	(*Embedding)(nil),          // 2: encoder.Embedding
}
var file_encoder_proto_depIdxs = []int32{
	2, // 0: encoder.EncodeTextResponse.embedding:type_name -> encoder.Embedding
	0, // 1: encoder.Encoder.EncodeText:input_type -> encoder.EncodeTextRequest
	1, // 2: encoder.Encoder.EncodeText:output_type -> encoder.EncodeTextResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_encoder_proto_init() }
func file_encoder_proto_init() {
	if File_encoder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_encoder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncodeTextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encoder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncodeTextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encoder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Embedding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_encoder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_encoder_proto_goTypes,
		DependencyIndexes: file_encoder_proto_depIdxs,
		MessageInfos:      file_encoder_proto_msgTypes,
	}.Build()
	File_encoder_proto = out.File
	file_encoder_proto_rawDesc = nil
	file_encoder_proto_goTypes = nil
	file_encoder_proto_depIdxs = nil
}
